version: "3.9"
services:
  indiekit:
    container_name: indiekit
    image: getindiekit/indiekit
    restart: always
    build: .
    ports:
      - "${HTTP_PORT:-3000}:3000"
    environment:
      - GITHUB_TOKEN
      - MASTODON_ACCESS_TOKEN
      - MONGO_URL
      - PASSWORD_SECRET
      - SECRET
